vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
       carsandservices_images:
           uri_prefix: /images/carsandservices
           upload_destination: '%kernel.project_dir%/public/images/carsandservices'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
